IF NOT EXISTS(SELECT TOP 1 * FROM Data_Load.DAS_LoadedEvents WHERE EventFeed = 'AccountEventView')
BEGIN
	UPDATE Data_Load.DAS_LoadedEvents SET EventFeed = 'AccountEventView' WHERE EventFeed = 'AccountEvents'
END

IF DATABASE_PRINCIPAL_ID('ViewSpecificReadOnly') IS NOT NULL
BEGIN
	GRANT SELECT ON [Data_Pub].[DAS_Employer_Accounts] TO ViewSpecificReadOnly
	GRANT SELECT ON [Data_Pub].[DAS_Employer_LegalEntities] TO ViewSpecificReadOnly
	GRANT SELECT ON [Data_Pub].[DAS_Employer_PayeSchemes] TO ViewSpecificReadOnly
	GRANT SELECT ON [Data_Pub].[DAS_Commitments] TO ViewSpecificReadOnly
	GRANT SELECT ON [Data_Pub].[DAS_CalendarMonth] TO ViewSpecificReadOnly
	GRANT SELECT ON [Data_Pub].[DAS_LevyDeclarations] TO ViewSpecificReadOnly
END

Exec Data_Load.UpdateCalendarMonth

IF (SELECT COUNT(*) FROM [Data_Load].[DAS_Employer_Accounts] WHERE IsLatest = 1) = 0
BEGIN
	UPDATE [Data_Load].[DAS_Employer_Accounts]
	SET IsLatest = 1
	WHERE Id IN (SELECT	MAX([Id]) FROM [Data_Load].[DAS_Employer_Accounts] GROUP BY [DasAccountId])
END

IF (SELECT COUNT(*) FROM [Data_Load].[DAS_Employer_LegalEntities] WHERE IsLatest = 1) = 0
BEGIN
	UPDATE [Data_Load].[DAS_Employer_LegalEntities]
	SET IsLatest = 1
	WHERE Id IN (SELECT	MAX([Id]) FROM [Data_Load].[DAS_Employer_LegalEntities] GROUP BY [DasAccountId], [DasLegalEntityId])
END

IF (SELECT COUNT(*) FROM [Data_Load].[DAS_Employer_PayeSchemes] WHERE IsLatest = 1) = 0
BEGIN
	UPDATE [Data_Load].[DAS_Employer_PayeSchemes]
	SET IsLatest = 1
	WHERE Id IN (SELECT	MAX([Id]) FROM [Data_Load].[DAS_Employer_PayeSchemes] GROUP BY [DasAccountId], [Ref])
END

IF (SELECT COUNT(*) FROM [Data_Load].[DAS_Commitments] WHERE IsLatest = 1) = 0
BEGIN
	UPDATE [Data_Load].[DAS_Commitments]
	SET IsLatest = 1
	WHERE Id IN (SELECT	MAX([Id]) FROM [Data_Load].[DAS_Commitments] GROUP BY [ApprenticeshipID])
END

IF (SELECT COUNT(*) FROM [Data_Load].[DAS_LevyDeclarations] WHERE IsLatest = 1) = 0
BEGIN
	UPDATE [Data_Load].[DAS_LevyDeclarations]
	SET IsLatest = 1
	WHERE Id IN (SELECT	MAX([Id]) FROM [Data_Load].[DAS_LevyDeclarations] GROUP BY [PayeSchemeReference], [PayrollMonth], [PayrollYear])
END

IF (SELECT COUNT(*) FROM [PerformancePlatform].[PP_LastRun]) = 0
BEGIN
	INSERT INTO [PerformancePlatform].[PP_LastRun] ([DateTime]) VALUES ('2017-01-01 00:00:00')
END

TRUNCATE TABLE HMRC.Configuration_Data_Quality_Tests

INSERT INTO HMRC.Configuration_Data_Quality_Tests
    ( ColumnName 
    , ColumnNullable 
    , ColumnType
    , ColumnLength 
    , ColumnPrecision 
    , ColumnDefault 
    , RunColumnTests 
    , ColumnPatternMatching
    , ColumnMinValue
    , ColumnMaxValue
    , FlagStopLoadIfTestTextLenght 
    , FlagStopLoadIfTestIsNumeric 
    , FlagStopLoadIfTestPatternMatch 
    , FlagStopLoadIfTestValueRange 
    , FlagStopLoadIfTestDecimalPlaces 
    )
SELECT 'TaxPeriodStartYear' AS ColumnName, 1 AS ColumnNullable , 'INT' AS ColumnType, '' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '20[1-9][0-9]' AS ColumnPatternMatching, '2016' AS ColumnMinValue, '9999' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,1 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'TaxPeriodMonth' AS ColumnName, 1 AS ColumnNullable , 'INT' AS ColumnType, '' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '1' AS ColumnMinValue, '12' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,1 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'SchemePAYERef' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '14' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '[0-9][0-9][0-9]/[A-Z]%' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'AccountsOfficeRef' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '13' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'UniqueTaxReference' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '10' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'RegisteredName' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '56' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'RegisteredAddressLine1' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '35' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'RegisteredAddressLine2' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '35' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'RegisteredAddressLine3' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '35' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'RegisteredAddressLine4' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '35' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'RegisteredAddressLine5' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '35' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'RegisteredPostcode' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '10' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'RegisteredForeignCountry' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '35' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'CessationDate' AS ColumnName, 1 AS ColumnNullable , 'Date' AS ColumnType, '' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'AlternativeName' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '56' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'AlternativeAddressLine1' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '35' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'AlternativeAddressLine2' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '35' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'AlternativeAddressLine3' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '35' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'AlternativeAddressLine4' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '30' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'AlternativeAddressLine5' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '35' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'AlternativePostcode' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '10' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'AlternativeForeignCountry' AS ColumnName, 1 AS ColumnNullable , 'VARCHAR' AS ColumnType, '35' AS ColumnLength, '' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth1LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth1EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth1AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth2LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth2EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth2AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth3LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth3EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth3AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth4LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth4EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth4AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth5LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth5EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth5AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth6LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth6EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth6AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatch, '' AS ColumnMinValue, '' AS ColumnMaxValueing,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth7LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth7EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth7AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth8LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth8EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth8AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth9LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth9EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth9AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth10LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth10EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth10AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth11LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth11EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxMonth11AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear1LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear1EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear1AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear2LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear2EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear2AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear3LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear3EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear3AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear4LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear4EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear4AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear5LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear5EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear5AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear6LevyDueYearToDate' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear6EnglishFraction' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '5' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces
UNION ALL SELECT 'HistoricAdjustmentsTaxYear6AnnualAllowanceAmount' AS ColumnName, 1 AS ColumnNullable , 'DECIMAL' AS ColumnType, '18' AS ColumnLength, '2' AS ColumnPrecision, '' AS ColumnDefault, 1 as RunColumnTests, '' AS ColumnPatternMatching, '' AS ColumnMinValue, '' AS ColumnMaxValue,0 AS FlagStopLoadIfTestTextLenght,0 AS FlagStopLoadIfTestIsNumeric,0 AS FlagStopLoadIfTestPatternMatch,0 AS FlagStopLoadIfTestValueRange,0 AS FlagStopLoadIfTestDecimalPlaces

INSERT INTO [RoATP].[ProviderType]
VALUES
(1, 'MainProvider'),
(2, 'SupportingProvider'),
(3, 'EmployerProvider')
