CREATE TABLE [Data_Load].[DAS_Standard_JobRoles]
(
	[Id] BIGINT IDENTITY NOT NULL PRIMARY KEY,
	[StandardId] NVARCHAR(255) NOT NULL,
	[JobRole] NVARCHAR(255) NOT NULL,
	[UpdateDateTime] DATETIME NOT NULL DEFAULT (GETDATE())
)
