CREATE TABLE [Data_Load].[DAS_ProviderAddress]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[UkPrn] BIGINT NOT NULL,
	[ContactType] NVARCHAR(50) NOT NULL,
	[Primary] NVARCHAR(255) NULL,
	[Secondary] NVARCHAR(255) NULL,
	[Street] NVARCHAR(255) NULL,
	[Town] NVARCHAR(255) NULL,
	[Postcode] NVARCHAR(25) NULL,
	[UpdateDateTime] DATETIME NOT NULL DEFAULT (GETDATE())
)
