CREATE TABLE [Data_Load].[DAS_ProviderAlias]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[UkPrn] BIGINT NOT NULL,
	[Alias] NVARCHAR(255) NOT NULL,
	[UpdateDateTime] DATETIME NOT NULL DEFAULT (GETDATE())
)
