CREATE TABLE [Data_Load].[DAS_Framework_JobRoles]
(
	[Id] BIGINT IDENTITY NOT NULL PRIMARY KEY,
	[FrameworkId] NVARCHAR(50) NOT NULL,
	[Title] NVARCHAR(MAX) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[UpdateDateTime] DATETIME NOT NULL DEFAULT (GETDATE())
)
