CREATE TABLE [HMRC].[Data_History](
     SourceFile_ID [BIGINT]  NULL,
     [Record_ID] [BIGINT] NOT NULL,
	[TaxPeriodStartYear] [INT] NULL,
	[TaxPeriodMonth] [INT] NULL,
	[SchemePAYERef] [varchar](14) NULL,
	[AccountsOfficeRef] [varchar](13) NULL,
	[UniqueTaxReference] [varchar](10) NULL,
	[LevyDueYearToDate] [decimal](38, 6) NULL,
	[AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[EnglishFraction] [decimal](38, 6) NULL,
	[RegisteredName] [varchar](256) NULL,
	[RegisteredAddressLine1] [varchar](256) NULL,
	[RegisteredAddressLine2] [varchar](256) NULL,
	[RegisteredAddressLine3] [varchar](256) NULL,
	[RegisteredAddressLine4] [varchar](256) NULL,
	[RegisteredAddressLine5] [varchar](256) NULL,
	[RegisteredPostcode] [varchar](10) NULL,
	[RegisteredForeignCountry] [varchar](256) NULL,
	[CessationDate] [DATE] NULL,
	[AlternativeName] [varchar](256) NULL,
	[AlternativeAddressLine1] [varchar](256) NULL,
	[AlternativeAddressLine2] [varchar](256) NULL,
	[AlternativeAddressLine3] [varchar](256) NULL,
	[AlternativeAddressLine4] [varchar](256) NULL,
	[AlternativeAddressLine5] [varchar](256) NULL,
	[AlternativePostcode] [varchar](10) NULL,
	[AlternativeForeignCountry] [varchar](256) NULL,
	[HistoricAdjustmentsTaxMonth1LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth1EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth1AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth2LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth2EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth2AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth3LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth3EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth3AnnualAllowanceAmount] [decimal](38, 6) NULL,	
	[HistoricAdjustmentsTaxMonth4LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth4EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth4AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth5LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth5EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth5AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth6LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth6EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth6AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth7LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth7EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth7AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth8LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth8EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth8AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth9LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth9EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth9AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth10LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth10EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth10AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth11LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth11EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxMonth11AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear1LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear1EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear1AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear2LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear2EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear2AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear3LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear3EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear3AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear4LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear4EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear4AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear5LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear5EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear5AnnualAllowanceAmount] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear6LevyDueYearToDate] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear6EnglishFraction] [decimal](38, 6) NULL,
	[HistoricAdjustmentsTaxYear6AnnualAllowanceAmount] [decimal](38, 6) NULL,
     [Inserted_DateTime] [DATETIME] DEFAULT GETDATE(),
     [Inserted_By] [VARCHAR](255) DEFAULT System_user

)