
CREATE TABLE [HMRC].[DATA-Live](
	[tax_year] [bigint] NULL,
	[tax_month] [bigint] NULL,
	[emp_ref] [varchar](256) NULL,
	[accounting_office_reference] [varchar](256) NULL,
	[tax_ref_utr] [varchar](256) NULL,
	[levy_due_ytd] [decimal](38,6)NULL,
	[annual_levy_allowance_amount] [varchar](256) NULL,
	[ef_by_pay_bill_till_date] [varchar](256) NULL,
	[employer_name] [varchar](256) NULL,
	[employer_address_line_1] [varchar](256) NULL,
	[employer_address_line_2] [varchar](256) NULL,
	[employer_address_line_3] [varchar](256) NULL,
	[employer_address_line_4] [varchar](256) NULL,
	[employer_address_line_5] [varchar](256) NULL,
	[employer_post_code] [varchar](256) NULL,
	[employer_foreign_country] [varchar](256) NULL,
	[cessation_date] [varchar](256) NULL,
	[correspondance_name] [varchar](256) NULL,
	[correspondance_address_line_1] [varchar](256) NULL,
	[correspondance_address_line_2] [varchar](256) NULL,
	[correspondance_address_line_3] [varchar](256) NULL,
	[correspondance_address_line_4] [varchar](256) NULL,
	[correspondance_address_line_5] [varchar](256) NULL,
	[correspondance_post_code] [varchar](256) NULL,
	[correspondance_foreign_country] [varchar](256) NULL,
	[historical_levy_due_tax_month1] [decimal](38,6)NULL,
	[historical_ef_tax_month1] [decimal](38,6) NULL,
	[historical_levy_allowance_tax_month1] [decimal](38,6)NULL,
	[historical_levy_due_tax_month2] [decimal](38,6)NULL,
	[historical_ef_tax_month2] [decimal](38,6) NULL,
	[historical_levy_allowance_tax_month2] [decimal](38,6)NULL,
	[historical_levy_due_tax_month3] [decimal](38,6)NULL,
	[historical_ef_tax_month3] [decimal](38,6) NULL,
	[historical_levy_allowance_tax_month3] [decimal](38,6)NULL,
	[historical_levy_due_tax_month4] [decimal](38,6)NULL,
	[historical_ef_tax_month4] [decimal](38,6) NULL,
	[historical_levy_allowance_tax_month4] [decimal](38,6)NULL,
	[historical_levy_due_tax_month5] [decimal](38,6)NULL,
	[historical_ef_tax_month5] [decimal](38,6) NULL,
	[historical_levy_allowance_tax_month5] [decimal](38,6)NULL,
	[historical_levy_due_tax_month6] [decimal](38,6)NULL,
	[historical_ef_tax_month6] [decimal](38,6) NULL,
	[historical_levy_allowance_tax_month6] [decimal](38,6)NULL,
	[historical_levy_due_tax_month7] [decimal](38,6)NULL,
	[historical_ef_tax_month7] [decimal](38,6) NULL,
	[historical_levy_allowance_tax_month7] [decimal](38,6)NULL,
	[historical_levy_due_tax_month8] [decimal](38,6)NULL,
	[historical_ef_tax_month8] [decimal](38,6) NULL,
	[historical_levy_allowance_tax_month8] [decimal](38,6)NULL,
	[historical_levy_due_tax_month9] [decimal](38,6)NULL,
	[historical_ef_tax_month9] [decimal](38,6) NULL,
	[historical_levy_allowance_tax_month9] [decimal](38,6)NULL,
	[historical_levy_due_tax_month10] [decimal](38,6)NULL,
	[historical_ef_tax_month10] [decimal](38,6) NULL,
	[historical_levy_allowance_tax_month10] [decimal](38,6)NULL,
	[historical_levy_due_tax_month11] [decimal](38,6)NULL,
	[historical_ef_tax_month11] [decimal](38,6) NULL,
	[historical_levy_allowance_tax_month11] [decimal](38,6)NULL,
	[historical_adjustment_levy_due_previous_1] [decimal](38,6)NULL,
	[historical_adjustment_ef_previous_1] [decimal](38,6) NULL,
	[historical_adjustment_levy_allowance_previous_1] [decimal](38,6)NULL,
	[historical_adjustment_levy_due_previous_2] [decimal](38,6)NULL,
	[historical_adjustment_ef_previous_2] [decimal](38,6) NULL,
	[historical_adjustment_levy_allowance_previous_2] [decimal](38,6)NULL,
	[historical_adjustment_levy_due_previous_3] [decimal](38,6)NULL,
	[historical_adjustment_ef_previous_3] [decimal](38,6) NULL,
	[historical_adjustment_levy_allowance_previous_3] [decimal](38,6)NULL,
	[historical_adjustment_levy_due_previous_4] [decimal](38,6)NULL,
	[historical_adjustment_ef_previous_4] [decimal](38,6) NULL,
	[historical_adjustment_levy_allowance_previous_4] [decimal](38,6)NULL,
	[historical_adjustment_levy_due_previous_5] [decimal](38,6)NULL,
	[historical_adjustment_ef_previous_5] [decimal](38,6) NULL,
	[historical_adjustment_levy_allowance_previous_5] [decimal](38,6)NULL,
	[historical_adjustment_levy_due_previous_6] [decimal](38,6)NULL,
	[historical_adjustment_ef_previous_6] [decimal](38,6) NULL,
	[historical_adjustment_levy_allowance_previous_6] [decimal](38,6)NULL
)