CREATE VIEW [Data_Pub].[DAS_DataLocks]	AS 
	SELECT lock.[Id],
      lock.[DataLockId],
      lock.[ProcessDateTime],
      lock.[IlrFileName],
      lock.[UkPrn],
      lock.[Uln],
      lock.[LearnRefNumber],
      lock.[AimSeqNumber],
      lock.[PriceEpisodeIdentifier],
      lock.[ApprenticeshipId],
      lock.[EmployerAccountId],
      lock.[EventSource],
      lock.[HasErrors],
      lock.[IlrStartDate],
      lock.[IlrStandardCode],
      lock.[IlrProgrammeType],
      lock.[IlrFrameworkCode],
      lock.[IlrPathwayCode],
      lock.[IlrTrainingPrice],
      lock.[IlrEndpointAssessorPrice],
      lock.[IlrPriceEffectiveFromDate],
      lock.[IlrPriceEffectiveToDate],
      lock.[ErrorCode],
      lock.[SystemDescription],
      lock.[ApprenticeshipVersion],
      lock.[CollectionPeriodName],
      lock.[CollectionPeriodMonth],
      lock.[CollectionPeriodYear],
      lock.[IsPayable],
      lock.[TransactionType],
      lock.[Version],
      lock.[StartDate],
      lock.[StandardCode],
      lock.[ProgrammeType],
      lock.[FrameworkCode],
      lock.[PathwayCode],
      lock.[NegotiatedPrice],
      lock.[EffectiveDate],
      aim.[NumberOfLearnersWithACT1],
      aim.[NumberOfLearnersWithACT2]
  FROM 
		[Data_Load].[DAS_DataLocks] lock
		LEFT JOIN  [Data_Load].[DAS_ValidAims] aim
		ON	aim.[UkPrn] = lock.[UkPrn]
