CREATE PROCEDURE [Data_Load].[SaveLevyDeclaration]
	@DasAccountId NVARCHAR(100),
    @LevyDeclarationId BIGINT,
    @PayeSchemeReference NVARCHAR(20),
	@LevyDueYearToDate DECIMAL(18,5) = NULL,
    @LevyAllowanceForYear DECIMAL(18,5) = NULL,
	@SubmissionDate DATETIME = NULL,
    @SubmissionId BIGINT,
    @PayrollYear NVARCHAR(10),
    @PayrollMonth TINYINT,
    @CreatedDate DATETIME,
    @EndOfYearAdjustment BIT,
    @EndOfYearAdjustmentAmount DECIMAL(18,5) = NULL,
    @DateCeased DATETIME = NULL,
	@InactiveFrom DATETIME = NULL,
    @InactiveTo DATETIME = NULL,
    @HmrcSubmissionId BIGINT,
    @EnglishFraction DECIMAL(18,5),
    @TopupPercentage DECIMAL(18,5),
	@TopupAmount DECIMAL(18,5),
	@LevyDeclaredInMonth DECIMAL(18,5) = NULL,
	@LevyAvailableInMonth DECIMAL(18,5) = NULL
AS
	INSERT INTO [Data_Load].DAS_LevyDeclarations
	(
		[DasAccountId],
		[LevyDeclarationId],
		[PayeSchemeReference],
		[LevyDueYearToDate],
		[LevyAllowanceForYear],
		[SubmissionDate],
		[SubmissionId],
		[PayrollYear],
		[PayrollMonth],
		[CreatedDate],
		[EndOfYearAdjustment],
		[EndOfYearAdjustmentAmount],
		[DateCeased],
		[InactiveFrom],
		[InactiveTo],
		[HmrcSubmissionId],
		[EnglishFraction],
		[TopupPercentage],
		[TopupAmount],
		[LevyDeclaredInMonth],
		[LevyAvailableInMonth]
	)
	VALUES
	(
		@DasAccountId,
		@LevyDeclarationId,
		@PayeSchemeReference,
		@LevyDueYearToDate,
		@LevyAllowanceForYear,
		@SubmissionDate,
		@SubmissionId,
		@PayrollYear,
		@PayrollMonth,
		@CreatedDate,
		@EndOfYearAdjustment,
		@EndOfYearAdjustmentAmount,
		@DateCeased,
		@InactiveFrom,
		@InactiveTo,
		@HmrcSubmissionId,
		@EnglishFraction,
		@TopupPercentage,
		@TopupAmount,
		@LevyDeclaredInMonth,
		@LevyAvailableInMonth
	)
