CREATE PROCEDURE [Data_Load].[SavePayment]
	@PaymentId NVARCHAR(100),
	@UkPrn BIGINT,
	@Uln BIGINT,
	@EmployerAccountId NVARCHAR(100) = NULL,
	@ApprenticeshipId BIGINT = NULL,
	@DeliveryMonth INT,
	@DeliveryYear INT,
	@CollectionMonth INT,
	@CollectionYear INT,
	@EvidenceSubmittedOn DATETIME,
	@EmployerAccountVersion NVARCHAR(50),
	@ApprenticeshipVersion NVARCHAR(50),
	@FundingSource NVARCHAR(25),
	@TransactionType NVARCHAR(50),
	@Amount DECIMAL,
	@StandardCode BIGINT = NULL,
	@FrameworkCode INT = NULL,
	@ProgrammeType INT = NULL,
	@PathwayCode INT = NULL,
	@ContractType NVARCHAR(50)
AS
	INSERT INTO [Data_Load].DAS_Payments 
	(
		[PaymentId],
		[UkPrn],
		[Uln],
		[EmployerAccountId],
		[ApprenticeshipId],
		[DeliveryMonth],
		[DeliveryYear],
		[CollectionMonth],
		[CollectionYear],
		[EvidenceSubmittedOn],
		[EmployerAccountVersion],
		[ApprenticeshipVersion],
		[FundingSource],
		[TransactionType],
		[Amount],
		[StandardCode],
		[FrameworkCode],
		[ProgrammeType],
		[PathwayCode],
		[ContractType] 
	)
	VALUES
	(
		@PaymentId,
		@UkPrn,
		@Uln,
		@EmployerAccountId,
		@ApprenticeshipId,
		@DeliveryMonth,
		@DeliveryYear,
		@CollectionMonth,
		@CollectionYear,
		@EvidenceSubmittedOn,
		@EmployerAccountVersion,
		@ApprenticeshipVersion,
		@FundingSource,
		@TransactionType,
		@Amount,
		@StandardCode,
		@FrameworkCode,
		@ProgrammeType,
		@PathwayCode,
		@ContractType
	)